name: Deploy to EKS with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name vprofile-eks

    - name: Debug Ingress Controller Pod
      run: |
        kubectl get pods -n ingress-nginx -o wide
        kubectl describe pod -n ingress-nginx -l app.kubernetes.io/component=controller
        kubectl logs -n ingress-nginx -l app.kubernetes.io/component=controller --tail=50

    - name: Checking Ingress Controller readiness
      run: |
        echo "Checking Ingress Controller readiness..."
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=300s

    - name: Checking Ingress Admission Webhook endpoints
      run: |
        echo "Checking Ingress Admission Webhook endpoints..."
        kubectl get endpoints ingress-nginx-controller-admission -n ingress-nginx

    - name: Deploy using Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        cluster-name: vprofile-eks
        chart-path: helm/vprofilecharts
        namespace: default
        values: "appimage=***/vprofileapp,apptag=32"
        name: vprofile-stack
        action: upgrade
        helm-wait: true
        atomic: true
